### ISSUE TITLE
[NUHS] Multi-Org Post - Edit API enhancements

### ISSUE THREAD

**Issue by suryaiiit** [rewardz/Feeds#100]
- [x] Add departments = array of ids in Get Post API 
- [x] Shared_with = add new value for Custom - Org/Dept
- [x] Updating Post API should save shared_with, and also orgs/depts
- [x] Update POST API & Save POST API - should be consistent (response should have organizations & departments)

**Comment by ankits1626** [comment]
@suryaiiit here are the estimates for iOS:

- [ ] Update feed creation - 3 days
- [ ] Update feed edit - 2 days
- [ ] Update Preview - 3 days
- [ ] Configure org/department view to show teams  - 1 day
- [ ] Update APIs - 2 days

Note: These estimates are subject to change depending upon the designs proposed later
