### ISSUE TITLE
NUHS app post/polls List issue with self department Post

### ISSUE THREAD

**Issue by yatishTrootech** [rewardz/Feeds#125]
In NUHS app if a Post is created with self department then it is still showing to another department of the same ORG

**Comment by qanaveen1111** [comment]
- [ ] when creating My department post --/feeds/api/posts/?page=1
- [ ] 2. Like the post--/feeds/api/posts/2096/appreciate/
- [ ] 3. comment to post --/feeds/api/posts/2096/comments/
- [ ] 4.

**Comment by qanaveen1111** [comment]
- [ ] ORG-Parent (Post-My department) -Created post from parent Org -user1@nuhs.edu.sg (pharmacy dept)and login with same Org but different dept user -user2@nuhs.org ( Dept Diagnostics) so post is not displaying 
- [ ]

**Comment by yatishTrootech** [comment]
org1  - dept1  = user1, user2 
org2  - dept2  = user3, user4
if user 1 create a polls having org1 and choose custom option(organization department) select dept2

polls ORG = org1 (should be null)
polls dept = dept 2
shared_with=ORG_DEPT

user2 can access the polls which is wrong

```polls Shared with ORG_DEPT is not working```

**Comment by yatishTrootech** [comment]
On Hold Reason : https://github.com/rewardz/Feeds/issues/122#issuecomment-1498960498
