### ISSUE TITLE
Feeds DOC for testing covering all test cases and scenarios

### ISSUE THREAD

**Issue by yatishTrootech** [rewardz/Feeds#141]
For the feeds repo 
Post/polls, Appreciations, Rico, and Feedback posts sometimes fail and have issues with visibility according to shared with the flag of that post So prepare a document covering all the scenarios and test cases which is helpful for QA team to complete test covering all the scenarios for that 

DOC: https://docs.google.com/document/d/1Lja7CVrivNseWvfdVszlvgEAMTNXA1BVu2rquKI-uBo/edit?usp=sharing

Linked Issues:
[[Feedback] Closed feedbacks are throwing errors #4832](https://github.com/rewardz/skor/issues/4832)

[Top Hero Api Changes #4777](https://github.com/rewardz/skor/issues/4777)

[[McD] In Profile Appreciation for Receive , Given ,post &poll count is displaying wrong #4763](https://github.com/rewardz/skor/issues/4763)

[[IFZA]User tag in comment notification is getting as feed not found #4750](https://github.com/rewardz/skor/issues/4750)

[organization recognition search only searches the start of name #127](https://github.com/rewardz/Feeds/issues/127)

[[Feedback] User Unable to access comments and post detail #129](https://github.com/rewardz/Feeds/issues/129)

[Issue With shared with "ORGANIZATION_DEPARTMENTS" posts/polls #122](https://github.com/rewardz/Feeds/issues/122)

[NUHS app post/polls List issue with self department and ORGANIZATION_DEPARTMENT Post #125](https://github.com/rewardz/Feeds/issues/125)

[Don't use affiliated Orgs to get posts everywhere #4569](https://github.com/rewardz/skor/issues/4569)

[[BOUS- M2]- Send Greetings with attachments #4026](https://github.com/rewardz/skor/issues/4026)

[[MCD]Backend issues #4377](https://github.com/rewardz/skor/issues/4377)

[Feedback List API - Affiliated Orgs #4224](https://github.com/rewardz/skor/issues/4224)

[[McD] Client feedback shared by Sudhanshu(Backend issues) #4235](https://github.com/rewardz/skor/issues/4235)

[[NUHS] Multi-org Post - User who created the post should be able to view #3855](https://github.com/rewardz/skor/issues/3855)

**Comment by yatishTrootech** [comment]
Hey @suryaiiit  At the time of the creation of the Feedback we create a post in the backend [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/functions.py#L22) 
By default, it is taking ```shared_with=self_department``` and we are setting only ORGS(of creator) in the post model [here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/functions.py#L27) departments are blank for post

But if we create a regular/normal from post/polls section and post that is ```shared with = self department``` then we are setting departments in the post here ORGS are null [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/serializers.py#L458) 

if we go according to the normal post logic feedback is following the opposite logic for it, Should set departments instead of ORGS

Should we make this change here for feedback post?

**Comment by yatishTrootech** [comment]
Hey @suryaiiit We Have a Custom option while creating post/polls

Custom (```shared_with=ORGANIZATION_DEPARTMENTS``` **40**) 
Front end will pass organizations if all departments are selected otherwise I will get only departments

EG:
ORGA: DeptA1, DeptA2
ORGB: DeptB1, DepatB2

for posts/polls custom selection 

**Case 1**: if selected DeptA1, DeptB1, DepatB2 and create then front end will send me 

organizations = [ORGB]
departments = [DeptA1, DeptB1, DepatB2]


**Case 2:** If selected DeptA1, DeptA2, DeptB1, DepatB2 and create then front end will send me 

organizations = [ORGA, ORGB]
departments = [DeptA1, DeptB1, DepatB2]



**Case 3:** If selected DeptA1, DeptB1 and create then front end will send me 
organizations = []
departments = [DeptA1, DeptB1,]


is this correct @suyeshkandpal28 ?

**Comment by yatishTrootech** [comment]
> Hey @suryaiiit We Have a Custom option while creating post/polls
> 
> Custom (`shared_with=ORGANIZATION_DEPARTMENTS` **40**) Front end will pass organizations if all departments are selected otherwise I will get only departments
> 
> EG: ORGA: DeptA1, DeptA2 ORGB: DeptB1, DepatB2
> 
> for posts/polls custom selection
> 
> **Case 1**: if selected DeptA1, DeptB1, DepatB2 and create then front end will send me
> 
> organizations = [ORGB] departments = [DeptA1, DeptB1, DepatB2]
> 
> **Case 2:** If selected DeptA1, DeptA2, DeptB1, DepatB2 and create then front end will send me
> 
> organizations = [ORGA, ORGB] departments = [DeptA1, DeptB1, DepatB2]
> 
> **Case 3:** If selected DeptA1, DeptB1 and create then front end will send me organizations = [] departments = [DeptA1, DeptB1,]
> 
> Is this correct @suyeshkandpal28 ?

If yes then for case 3 post is working fine because at the time of creation, we are updating the initial data from this function [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/views.py#L182) and it updates the ORG if [multi org is not enabled ](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/views.py#L129)  but while creating polls we are setting ORG in initial data [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/views.py#L298)
Which looks wrong to me Should I do the same for updating ORG here in the initial data?

@suryaiiit

**Comment by suyeshkandpal28** [comment]
> Hey @suryaiiit We Have a Custom option while creating post/polls
> 
> Custom (`shared_with=ORGANIZATION_DEPARTMENTS` **40**) Front end will pass organizations if all departments are selected otherwise I will get only departments
> 
> EG: ORGA: DeptA1, DeptA2 ORGB: DeptB1, DepatB2
> 
> for posts/polls custom selection
> 
> **Case 1**: if selected DeptA1, DeptB1, DepatB2 and create then front end will send me
> 
> organizations = [ORGB] departments = [DeptA1, DeptB1, DepatB2]
> 
> **Case 2:** If selected DeptA1, DeptA2, DeptB1, DepatB2 and create then front end will send me
> 
> organizations = [ORGA, ORGB] departments = [DeptA1, DeptB1, DepatB2]
> 
> **Case 3:** If selected DeptA1, DeptB1 and create then front end will send me organizations = [] departments = [DeptA1, DeptB1,]
> 
> is this correct @suyeshkandpal28 ?

Yes its correct @yatishTrootech

**Comment by yatishTrootech** [comment]
In APP if we create a custom post through postman without setting Enable Multi Organization Post & Poll
 it should throw

**Comment by yatishTrootech** [comment]
> Hey @suryaiiit At the time of the creation of the Feedback we create a post in the backend [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/functions.py#L22) By default, it is taking `shared_with=self_department` and we are setting only ORGS(of creator) in the post model [here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/functions.py#L27) departments are blank for post
> 
> But if we create a regular/normal from post/polls section and post that is `shared with = self department` then we are setting departments in the post here ORGS are null [Here](https://github.com/rewardz/Feeds/blob/02a54c51fd4dd062695aba465b15554298e8d6d0/feeds/serializers.py#L458)
> 
> if we go according to the normal post logic feedback is following the opposite logic for it, Should set departments instead of ORGS
> 
> Should we make this change here for feedback post?

Dont consider shared_witjh for feedback posts

**Comment by qanaveen1111** [comment]
Date-27-4-23
Server-prashant.skordev.com 

MAC-D Happi app:-

 For post/polls (post_type=USER_CREATED_POST or USER_CREATED_POLL):  

 Case-1: if post is shared_with = self_department (departments only)
            a) If the user is an admin they can see all the posts which are not belongs to them of  
                 Their ORG/DEPT/post created by Themselves
            b) Normal user must belongs to creator's Department or receiver of that post then only  
                 he can access that post

Test Scenarios

**Comment by qanaveen1111** [comment]
NUHS App-

    `Case-1: if post is shared_with = self_department (my departments only)`
            `a) Admin from creator's ORG can access this post `
           ` b) Normal user must belongs to creator/ creator's department  can access the post`


### Poll to My Dept--> Poll will display only to particular department of logged in user

- [ ]  Org-Parent (Poll type- My Dept)- Created poll from [[user1@nuhs.edu.sg] (Pharmacy dept )to My dept and login with diagnosis dept user-[[user3@nuhs.edu.sg] poll is not displaying poll is displaying for only Pharmacy dept and login with child Org user poll is not displaying
- [ ]  Org-Child (Poll type- My Dept)- Created poll from [[[admin@test8.com](Clinical dept )to My dept and login with Cardic dept poll is not displaying poll is displaying for only Clinical dept
