### ISSUE TITLE
send shorter parameter to celery

### ISSUE THREAD

**Issue by dryice** [rewardz/Feeds#211]
this is a follow up to https://github.com/rewardz/Feeds/pull/207/files

A little worried the accessible_user list could get too big and exceed SQS limitation. Best to move the calculation of accessible_user into the celery task.

**Comment by rishireward** [comment]
please test out the post and poll creation on rishi server
try to create and share across all the departments/users of org

**Comment by Revanthsanaboyina** [comment]
hi @rishireward  Verified the below scenarios on rishi server for Cerra global latest app
1. Create post & poll with my department 
2. Create post & poll with my organization
3. Edit the post 
4. Delete the post & poll
5. Pin  and unpin the post & poll 
6. Comment on post & poll  ( self edit comment and delete comment  and admin user edit and delete other users comments)
7. Post create from normal user
8. Poll create and submit option
9. Test reactions 
10. Test report abuse option
11. Test filters 
12. Test search option 
13. Create post & poll with amplify 
14.  Test Comment like
