### ISSUE TITLE
[NUHS] Multi-org Post and Poll - Feeds

### ISSUE THREAD

**Issue by suryaiiit** [rewardz/Feeds#56]
- https://github.com/rewardz/skor/issues/2503

**Comment by srivatsamedavaram** [comment]
Admin 
https://www.figma.com/proto/9encnmNnjefdVfG3oBjeo9/Newsfeed-on-web?page-id=0%3A4157&node-id=0%3A5014&viewport=2638%2C2149%2C0.5&scaling=min-zoom&starting-point-node-id=0%3A5014&show-proto-sidebar=1
